name: workflow_run

on:
  workflow_run:
    workflows: [test]
    types: [completed]

jobs:
  job1:
    runs-on: ubuntu-latest
    if:  ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "Workflow triggered by other workflow"
